/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmehBtn {
        "color": 'primary' | 'secondary' | 'tertiary';
        "outline": boolean;
        "theme": 'light' | 'dark' | 'auto';
        "type": 'button' | 'reset' | 'submit';
    }
    interface AmehContainer {
    }
    interface AmehIcon {
        "icon": string;
        "size": 'sm' | 'md' | 'lg';
    }
    interface AmehNavbar {
        "placement": 'fixed-top' | 'fixed-bottom' | 'sticky-top';
        "theme": 'light' | 'dark' | 'auto';
    }
    interface AmehNavbarItem {
        "theme": 'light' | 'dark' | 'auto';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAmehBtnElement extends Components.AmehBtn, HTMLStencilElement {
    }
    var HTMLAmehBtnElement: {
        prototype: HTMLAmehBtnElement;
        new (): HTMLAmehBtnElement;
    };
    interface HTMLAmehContainerElement extends Components.AmehContainer, HTMLStencilElement {
    }
    var HTMLAmehContainerElement: {
        prototype: HTMLAmehContainerElement;
        new (): HTMLAmehContainerElement;
    };
    interface HTMLAmehIconElement extends Components.AmehIcon, HTMLStencilElement {
    }
    var HTMLAmehIconElement: {
        prototype: HTMLAmehIconElement;
        new (): HTMLAmehIconElement;
    };
    interface HTMLAmehNavbarElement extends Components.AmehNavbar, HTMLStencilElement {
    }
    var HTMLAmehNavbarElement: {
        prototype: HTMLAmehNavbarElement;
        new (): HTMLAmehNavbarElement;
    };
    interface HTMLAmehNavbarItemElement extends Components.AmehNavbarItem, HTMLStencilElement {
    }
    var HTMLAmehNavbarItemElement: {
        prototype: HTMLAmehNavbarItemElement;
        new (): HTMLAmehNavbarItemElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ameh-btn": HTMLAmehBtnElement;
        "ameh-container": HTMLAmehContainerElement;
        "ameh-icon": HTMLAmehIconElement;
        "ameh-navbar": HTMLAmehNavbarElement;
        "ameh-navbar-item": HTMLAmehNavbarItemElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AmehBtn {
        "color"?: 'primary' | 'secondary' | 'tertiary';
        "outline"?: boolean;
        "theme"?: 'light' | 'dark' | 'auto';
        "type"?: 'button' | 'reset' | 'submit';
    }
    interface AmehContainer {
    }
    interface AmehIcon {
        "icon": string;
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface AmehNavbar {
        "placement"?: 'fixed-top' | 'fixed-bottom' | 'sticky-top';
        "theme"?: 'light' | 'dark' | 'auto';
    }
    interface AmehNavbarItem {
        "theme"?: 'light' | 'dark' | 'auto';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ameh-btn": AmehBtn;
        "ameh-container": AmehContainer;
        "ameh-icon": AmehIcon;
        "ameh-navbar": AmehNavbar;
        "ameh-navbar-item": AmehNavbarItem;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ameh-btn": LocalJSX.AmehBtn & JSXBase.HTMLAttributes<HTMLAmehBtnElement>;
            "ameh-container": LocalJSX.AmehContainer & JSXBase.HTMLAttributes<HTMLAmehContainerElement>;
            "ameh-icon": LocalJSX.AmehIcon & JSXBase.HTMLAttributes<HTMLAmehIconElement>;
            "ameh-navbar": LocalJSX.AmehNavbar & JSXBase.HTMLAttributes<HTMLAmehNavbarElement>;
            "ameh-navbar-item": LocalJSX.AmehNavbarItem & JSXBase.HTMLAttributes<HTMLAmehNavbarItemElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
